### ISSUE TITLE
Android build crashes when trying to initialise the SDK

### ISSUE THREAD

**Issue by suejon** [beaconinside/cordova-sdk#2]
I am trying to get a simple cordova project working with the beaconinside SDK, which resembles the simple example in the README.md:

```
onDeviceReady: function() {
  this.receivedEvent('deviceready');

  // Change YOUR_APP_TOKEN with your own token
  window.initBeaconinsideSDK("YOUR_APP_TOKEN");
}
```
*replacing YOUR_APP_TOKEN with my own app's token from the beaconinside web app.

However, after following the instructions, the Android build crashes upon startup.

Attempted to reinstall plugins and platforms but the problem still persists. 

The adb log displays the following fatal errors upon crashing:

--------- beginning of crash
07-25 16:33:21.293  9503  9558 E AndroidRuntime: FATAL EXCEPTION: BeaconScanning
07-25 16:33:21.293  9503  9558 E AndroidRuntime: Process: com.ionicframework.beaoninsideapp988738, PID: 9503
07-25 16:33:21.293  9503  9558 E AndroidRuntime: java.lang.NoClassDefFoundError: com.beaconinside.a.a.a$b
07-25 16:33:21.293  9503  9558 E AndroidRuntime: 	at com.beaconinside.androidsdk.e.a(Unknown Source)
07-25 16:33:21.293  9503  9558 E AndroidRuntime: 	at com.beaconinside.androidsdk.BeaconService.a(Unknown Source)
07-25 16:33:21.293  9503  9558 E AndroidRuntime: 	at com.beaconinside.androidsdk.BeaconService.j(Unknown Source)
07-25 16:33:21.293  9503  9558 E AndroidRuntime: 	at com.beaconinside.androidsdk.BeaconService.r(Unknown Source)
07-25 16:33:21.293  9503  9558 E AndroidRuntime: 	at com.beaconinside.androidsdk.BeaconService.k(Unknown Source)
07-25 16:33:21.293  9503  9558 E AndroidRuntime: 	at com.beaconinside.androidsdk.BeaconService$b.handleMessage(Unknown Source)
07-25 16:33:21.293  9503  9558 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-25 16:33:21.293  9503  9558 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
07-25 16:33:21.293  9503  9558 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)
07-25 16:33:21.429  1943  4855 I chatty  : uid=1000(system) Binder_10 expire 4 lines

**Comment by bashtian** [comment]
Thank you for your report. This issue should be fixed with the latest commit.
