### ISSUE TITLE
Error: Failed to get absolute path to installed module

### ISSUE THREAD

**Issue by Florian007** [beaconinside/cordova-sdk#5]
Installation error on Windows 10 for Android with command:
cordova plugin add https://github.com/beaconinside/cordova-sdk

Error: 
Failed to get absolute path to installed module

The same happens when downloading the plugin before and installing it locally.

**Comment by bashtian** [comment]
This seems to be a cordova problem, you can try the solutions mentioned here:
https://stackoverflow.com/questions/43856285/failed-to-get-absolute-path-to-installed-module

**Comment by Florian007** [comment]
Thank you. Downgrading to Cordova 6.5 worked.
